spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moyamoyu?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true # Flyway활성화
    baseline-on-migrate: false
  data:
    redis:
      port: 6379
      host: localhost
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.timeout: 5000

springdoc:
  swagger-ui:
    path: /api/docs