spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moyamoyu?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true # Flyway활성화
    baseline-on-migrate: false
  data:
    redis:
      port: 6379
      host: localhost